# Generated by Django 5.1.4 on 2025-01-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/neymar.jpg', upload_to='products/'),
        ),
    ]
